[package]
name = "text"
description = "a text editor"
version = "0.1.0"
edition = "2021"

[dependencies]
gpui = { git = "https://github.com/zed-industries/zed" }
unicode-segmentation = "1.12"
ropey = "1.6.1"
smallvec = "1.13.2"

[package.metadata.bundle]
name = "text"
identifier = "de.nullwire.text"
icon = ["assets/icon*.png"]
